# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "local"
hooks = [
  { id = "bun-test", name = "bun test", entry = "bun test", language = "system", pass_filenames = false, always_run = true }
]
